// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFYr-4I73PBmk8g5_c2GmqCfGEfdh8hOg',
    appId: '1:202348341324:web:2af1da11be8eca5790ace9',
    messagingSenderId: '202348341324',
    projectId: 'flutter-demo-8f417',
    authDomain: 'flutter-demo-8f417.firebaseapp.com',
    storageBucket: 'flutter-demo-8f417.firebasestorage.app',
    measurementId: 'G-7PZ58GJVGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7t39J9TaiZrscy3oXqUsOg07IjrvP0dY',
    appId: '1:202348341324:android:57424ad00ae63d9390ace9',
    messagingSenderId: '202348341324',
    projectId: 'flutter-demo-8f417',
    storageBucket: 'flutter-demo-8f417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTs_6QFFMQDwVr7SBiFprNwFYNHaxP9w',
    appId: '1:202348341324:ios:fb4daeff201df97290ace9',
    messagingSenderId: '202348341324',
    projectId: 'flutter-demo-8f417',
    storageBucket: 'flutter-demo-8f417.firebasestorage.app',
    iosBundleId: 'com.intelligence.campusrun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYTs_6QFFMQDwVr7SBiFprNwFYNHaxP9w',
    appId: '1:202348341324:ios:412107bf88e6369990ace9',
    messagingSenderId: '202348341324',
    projectId: 'flutter-demo-8f417',
    storageBucket: 'flutter-demo-8f417.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFYr-4I73PBmk8g5_c2GmqCfGEfdh8hOg',
    appId: '1:202348341324:web:2caca153d6a938f690ace9',
    messagingSenderId: '202348341324',
    projectId: 'flutter-demo-8f417',
    authDomain: 'flutter-demo-8f417.firebaseapp.com',
    storageBucket: 'flutter-demo-8f417.firebasestorage.app',
    measurementId: 'G-M8GBFHBTEG',
  );
}
